CREATE TABLE IF NOT EXISTS test_item_prd_ref_link (
  project_code VARCHAR(64) NOT NULL DEFAULT 'fitness-agent',
  link_id VARCHAR(16) PRIMARY KEY,
  item_id VARCHAR(64) NOT NULL REFERENCES test_item_detail(item_id) ON DELETE CASCADE, prd_ref_id VARCHAR(32) NOT NULL REFERENCES prd_reference(prd_ref_id)
);
CREATE INDEX IF NOT EXISTS idx_test_item_prd_ref_link_item ON test_item_prd_ref_link(item_id);

INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00001', 'A1-MEMORY-001', 'PRD_7_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00004', 'A1-OUTBOX-002', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00006', 'A2-S02-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00008', 'A2-S02-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00012', 'A2-S02-004', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00014', 'A2-S03-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00019', 'A5-MULTI-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00022', 'A6-MEDICAL-001', 'PRD_5_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00026', 'A6-SAFETY-001', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00047', 'B2-LEN-001', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00052', 'B2-OWN-001', 'PRD_6_PERM') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00057', 'B3-CLAIM-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00059', 'B3-CROSS-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00065', 'B3-W-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00072', 'B4-PREP-002', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00080', 'B6-OBS-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00084', 'B6-TIMEOUT-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00087', 'C1-CONF-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00089', 'C1-CONF-002', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00091', 'C1-CONF-003', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00093', 'C1-CONF-004', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00095', 'C1-CONF-005', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00100', 'C1-ENTRY-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00103', 'C1-ENTRY-002', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00106', 'C1-ENTRY-003', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00110', 'C1-ENTRY-004', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00113', 'C1-ENTRY-005', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00116', 'C1-ENTRY-006', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00119', 'C1-ENTRY-007', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00121', 'C1-INTENT-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00123', 'C1-INTENT-002', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00125', 'C1-INTENT-003', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00127', 'C1-INTENT-004', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00129', 'C1-INTENT-005', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00131', 'C1-INTENT-006', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00133', 'C1-INTENT-007', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00135', 'C1-INTENT-008', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00137', 'C1-MACRO-001', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00139', 'C1-MACRO-002', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00141', 'C1-MACRO-003', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00143', 'C1-MACRO-004', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00145', 'C1-MACRO-005', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00147', 'C1-MACRO-006', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00149', 'C1-MACRO-007', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00151', 'C1-MACRO-008', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00153', 'C1-MACRO-009', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00155', 'C1-MACRO-010', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00157', 'C1-MACRO-011', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00160', 'C1-SAFE-001', 'PRD_4_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00163', 'C1-SAFE-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00164', 'C1-SAFE-002', 'PRD_4_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00167', 'C1-SAFE-003', 'PRD_4_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00170', 'C1-SAFE-004', 'PRD_4_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00173', 'C1-SAFE-005', 'PRD_4_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00176', 'C1-SAFE-006', 'PRD_4_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00178', 'C1-SESSION-001', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00180', 'C1-SESSION-002', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00182', 'C1-SESSION-003', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00184', 'C1-SESSION-004', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00186', 'C1-SESSION-005', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00188', 'C1-SESSION-006', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00190', 'C1-SESSION-007', 'PRD_4_5') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00192', 'C1-STRAT-001', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00194', 'C1-STRAT-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00195', 'C1-STRAT-002', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00197', 'C1-STRAT-003', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00199', 'C1-STRAT-004', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00201', 'C1-STRAT-005', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00203', 'C1-STRAT-006', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00204', 'C1-SUM-001', 'PRD_4_6') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00205', 'C1-SUM-002', 'PRD_4_6') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00206', 'C1-SUM-003', 'PRD_4_6') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00207', 'C1-SUM-004', 'PRD_4_6') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00224', 'C2-MED-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00225', 'C2-MED-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00226', 'C2-MED-003', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00229', 'C2-PAYLOAD-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00232', 'C2-PAYLOAD-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00235', 'C2-PAYLOAD-003', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00238', 'C2-PAYLOAD-004', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00241', 'C2-PAYLOAD-005', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00244', 'C2-PAYLOAD-006', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00247', 'C2-PAYLOAD-007', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00255', 'C3-ALERT-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00270', 'C3-PAYLOAD-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00288', 'C4-CONF-001', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00290', 'C4-CONF-002', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00292', 'C4-CONF-003', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00293', 'C4-DATA-001', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00294', 'C4-DATA-002', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00295', 'C4-DATA-003', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00296', 'C4-KB-001', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00297', 'C4-KB-002', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00299', 'C4-MEM-001', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00301', 'C4-MEM-002', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00303', 'C4-PAY-001', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00305', 'C4-PAY-002', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00307', 'C4-PAY-003', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00309', 'C4-PAY-004', 'PRD_7_PAYLOAD') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00316', 'D2-OUT-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00343', 'E-RISK-001', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00346', 'E-RISK-002', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00350', 'E-RISK-003', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00354', 'E-RISK-004', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00358', 'E-RISK-005', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00360', 'E-RISK-006', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00362', 'E-RISK-007', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00364', 'E-RISK-008', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00366', 'E-RISK-009', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00368', 'E-RISK-010', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00375', 'E1-PATH-001', 'PRD_4_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00377', 'E1-PATH-002', 'PRD_4_4') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00379', 'E1-PATH-003', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00382', 'E1-PATH-005', 'PRD_4_7') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00387', 'E4-STAB-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00388', 'E4-STAB-003', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00393', 'F6-CAP-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00394', 'G1-PHASE-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00395', 'G1-PHASE-002', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00396', 'G1-PHASE-003', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00397', 'G1-PHASE-004', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00398', 'G1-PHASE-005', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00399', 'G1-PHASE-006', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00400', 'G1-PHASE-007', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00401', 'G2-QUEUE-003', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00402', 'G3-ERR-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00408', 'G8-T-001', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00409', 'G8-T-001', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00410', 'G8-T-002', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00411', 'G8-T-002', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00412', 'G8-T-003', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00413', 'G8-T-003', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00414', 'G8-T-004', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00415', 'G8-T-004', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00416', 'G8-T-005', 'PRD_8') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00417', 'G8-T-005', 'PRD_4_1') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00419', 'H1-S02-001', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00422', 'H1-S02-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00427', 'H1-S03-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00434', 'H1-S04-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00439', 'H1-S06-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00442', 'H2-FLD-001', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00444', 'H2-FLD-002', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00446', 'H2-FLD-003', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00448', 'H2-FLD-004', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00450', 'H2-FLD-005', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00452', 'H2-FLD-006', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00454', 'H2-FLD-007', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00456', 'H2-FLD-008', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00458', 'H2-FLD-009', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00460', 'H2-FLD-010', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00462', 'H2-FLD-011', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00464', 'H2-FLD-012', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00466', 'H2-FLD-013', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00468', 'H2-FLD-014', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00470', 'H2-FLD-015', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00472', 'H2-FLD-016', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00474', 'H2-FLD-017', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00476', 'H2-FLD-018', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00478', 'H2-FLD-019', 'PRD_7_3') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00483', 'H3-MEM-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id) VALUES ('PRL00488', 'H4-MGR-002', 'PRD_2') ON CONFLICT (link_id) DO NOTHING;

-- 数据导入（221 条）
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00001', 'A1-MEMORY-001', 'PRD_7_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00004', 'A1-OUTBOX-002', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00006', 'A2-S02-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00008', 'A2-S02-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00012', 'A2-S02-004', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00014', 'A2-S03-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00019', 'A5-MULTI-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00022', 'A6-MEDICAL-001', 'PRD_5_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00026', 'A6-SAFETY-001', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00047', 'B2-LEN-001', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00052', 'B2-OWN-001', 'PRD_6_PERM', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00057', 'B3-CLAIM-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00059', 'B3-CROSS-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00065', 'B3-W-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00072', 'B4-PREP-002', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00080', 'B6-OBS-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00084', 'B6-TIMEOUT-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00087', 'C1-CONF-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00089', 'C1-CONF-002', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00091', 'C1-CONF-003', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00093', 'C1-CONF-004', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00095', 'C1-CONF-005', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00100', 'C1-ENTRY-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00103', 'C1-ENTRY-002', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00106', 'C1-ENTRY-003', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00110', 'C1-ENTRY-004', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00113', 'C1-ENTRY-005', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00116', 'C1-ENTRY-006', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00119', 'C1-ENTRY-007', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00121', 'C1-INTENT-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00123', 'C1-INTENT-002', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00125', 'C1-INTENT-003', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00127', 'C1-INTENT-004', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00129', 'C1-INTENT-005', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00131', 'C1-INTENT-006', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00133', 'C1-INTENT-007', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00135', 'C1-INTENT-008', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00137', 'C1-MACRO-001', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00139', 'C1-MACRO-002', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00141', 'C1-MACRO-003', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00143', 'C1-MACRO-004', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00145', 'C1-MACRO-005', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00147', 'C1-MACRO-006', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00149', 'C1-MACRO-007', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00151', 'C1-MACRO-008', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00153', 'C1-MACRO-009', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00155', 'C1-MACRO-010', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00157', 'C1-MACRO-011', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00160', 'C1-SAFE-001', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00163', 'C1-SAFE-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00164', 'C1-SAFE-002', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00167', 'C1-SAFE-003', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00170', 'C1-SAFE-004', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00173', 'C1-SAFE-005', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00176', 'C1-SAFE-006', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00178', 'C1-SESSION-001', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00180', 'C1-SESSION-002', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00182', 'C1-SESSION-003', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00184', 'C1-SESSION-004', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00186', 'C1-SESSION-005', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00188', 'C1-SESSION-006', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00190', 'C1-SESSION-007', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00192', 'C1-STRAT-001', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00194', 'C1-STRAT-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00195', 'C1-STRAT-002', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00197', 'C1-STRAT-003', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00199', 'C1-STRAT-004', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00201', 'C1-STRAT-005', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00203', 'C1-STRAT-006', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00204', 'C1-SUM-001', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00205', 'C1-SUM-002', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00206', 'C1-SUM-003', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00207', 'C1-SUM-004', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00224', 'C2-MED-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00225', 'C2-MED-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00226', 'C2-MED-003', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00229', 'C2-PAYLOAD-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00232', 'C2-PAYLOAD-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00235', 'C2-PAYLOAD-003', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00238', 'C2-PAYLOAD-004', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00241', 'C2-PAYLOAD-005', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00244', 'C2-PAYLOAD-006', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00247', 'C2-PAYLOAD-007', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00255', 'C3-ALERT-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00270', 'C3-PAYLOAD-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00288', 'C4-CONF-001', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00290', 'C4-CONF-002', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00292', 'C4-CONF-003', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00293', 'C4-DATA-001', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00294', 'C4-DATA-002', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00295', 'C4-DATA-003', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00296', 'C4-KB-001', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00297', 'C4-KB-002', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00299', 'C4-MEM-001', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00301', 'C4-MEM-002', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00303', 'C4-PAY-001', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00305', 'C4-PAY-002', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00307', 'C4-PAY-003', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00309', 'C4-PAY-004', 'PRD_7_PAYLOAD', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00316', 'D2-OUT-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00343', 'E-RISK-001', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00346', 'E-RISK-002', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00350', 'E-RISK-003', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00354', 'E-RISK-004', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00358', 'E-RISK-005', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00360', 'E-RISK-006', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00362', 'E-RISK-007', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00364', 'E-RISK-008', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00366', 'E-RISK-009', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00368', 'E-RISK-010', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00375', 'E1-PATH-001', 'PRD_4_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00377', 'E1-PATH-002', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00379', 'E1-PATH-003', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00382', 'E1-PATH-005', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00387', 'E4-STAB-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00388', 'E4-STAB-003', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00393', 'F6-CAP-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00394', 'G1-PHASE-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00395', 'G1-PHASE-002', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00396', 'G1-PHASE-003', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00397', 'G1-PHASE-004', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00398', 'G1-PHASE-005', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00399', 'G1-PHASE-006', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00400', 'G1-PHASE-007', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00401', 'G2-QUEUE-003', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00402', 'G3-ERR-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00408', 'G8-T-001', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00409', 'G8-T-001', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00410', 'G8-T-002', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00411', 'G8-T-002', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00412', 'G8-T-003', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00413', 'G8-T-003', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00414', 'G8-T-004', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00415', 'G8-T-004', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00416', 'G8-T-005', 'PRD_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00417', 'G8-T-005', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00419', 'H1-S02-001', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00422', 'H1-S02-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00427', 'H1-S03-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00434', 'H1-S04-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00439', 'H1-S06-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00442', 'H2-FLD-001', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00444', 'H2-FLD-002', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00446', 'H2-FLD-003', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00448', 'H2-FLD-004', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00450', 'H2-FLD-005', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00452', 'H2-FLD-006', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00454', 'H2-FLD-007', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00456', 'H2-FLD-008', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00458', 'H2-FLD-009', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00460', 'H2-FLD-010', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00462', 'H2-FLD-011', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00464', 'H2-FLD-012', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00466', 'H2-FLD-013', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00468', 'H2-FLD-014', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00470', 'H2-FLD-015', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00472', 'H2-FLD-016', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00474', 'H2-FLD-017', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00476', 'H2-FLD-018', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00478', 'H2-FLD-019', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00483', 'H3-MEM-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00488', 'H4-MGR-002', 'PRD_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00489', 'ADD-MEMBER-COACH-001', 'PRD_5_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00490', 'ADD-MEMBER-COACH-001', 'PRD_5_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00491', 'ADD-MEMBER-COACH-001', 'PRD_5_12', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00492', 'ADD-CONTEXT-003', 'PRD_4_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00493', 'ADD-CONTEXT-003', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00494', 'ADD-CONTEXT-003', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00495', 'ADD-CONTEXT-004', 'PRD_4_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00496', 'ADD-CONTEXT-004', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00497', 'ADD-CONTEXT-004', 'PRD_7_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00498', 'ADD-EXEC-001-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00499', 'ADD-EXEC-001-R', 'PRD_4_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00500', 'ADD-EXEC-002-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00501', 'ADD-EXEC-002-R', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00502', 'ADD-EXEC-003-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00503', 'ADD-EXEC-003-R', 'PRD_4_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00504', 'ADD-EXEC-004-R', 'PRD_4_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00505', 'ADD-EXEC-004-R', 'PRD_4_10', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00506', 'ADD-EXEC-005-R', 'PRD_4_1', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00507', 'ADD-EXEC-005-R', 'PRD_4_2', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00508', 'ADD-EXEC-006-R', 'PRD_4_10', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00509', 'ADD-EXEC-006-R', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00510', 'ADD-EXEC-008-R', 'PRD_4_7', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00511', 'ADD-EXEC-008-R', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00512', 'ADD-EXEC-008-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00513', 'ADD-EXEC-009-R', 'PRD_4_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00514', 'ADD-EXEC-009-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00515', 'ADD-EXEC-009-R', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00516', 'ADD-EXEC-011-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00517', 'ADD-EXEC-011-R', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00518', 'ADD-EXEC-011-R', 'PRD_4_10', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00519', 'ADD-EXEC-012-R', 'PRD_4_6', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00520', 'ADD-EXEC-012-R', 'PRD_4_8', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00521', 'ADD-ADOPT-001', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00522', 'ADD-ADOPT-001', 'PRD_6_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00523', 'ADD-ADOPT-002', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00524', 'ADD-ADOPT-002', 'PRD_6_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00525', 'ADD-ADOPT-003', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00526', 'ADD-ADOPT-003', 'PRD_6_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00527', 'ADD-ADOPT-004', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00528', 'ADD-ADOPT-004', 'PRD_6_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00529', 'ADD-ADOPT-005', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00530', 'ADD-ADOPT-005', 'PRD_6_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00531', 'ADD-ADOPT-006', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00532', 'ADD-ADOPT-006', 'PRD_6_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00533', 'ADD-IMPACT-001', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00534', 'ADD-IMPACT-002', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00535', 'ADD-IMPACT-003', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00536', 'ADD-IMPACT-004', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00537', 'ADD-IMPACT-006', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00538', 'ADD-IMPACT-007', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00539', 'ADD-IMPACT-008', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00540', 'ADD-IMPACT-009', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00541', 'ADD-IMPACT-010', 'PRD_4_9', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00542', 'ADD-PLAN-003', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00543', 'ADD-PLAN-003', 'PRD_5_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00544', 'ADD-PLAN-004', 'PRD_4_4', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00545', 'ADD-PLAN-004', 'PRD_5_5', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00546', 'ADD-TEMPLATE-001', 'PRD_7_3', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_prd_ref_link (link_id, item_id, prd_ref_id, project_code) VALUES ('PRL00547', 'ADD-TEMPLATE-001', 'PRD_4_10', 'fitness-agent') ON CONFLICT (link_id) DO NOTHING;
