CREATE TABLE IF NOT EXISTS test_category_minor_scheme (
  project_code VARCHAR(64) NOT NULL DEFAULT 'fitness-agent',
  category_minor_id VARCHAR(64) PRIMARY KEY REFERENCES test_category_minor(category_minor_id),
  item_prefix VARCHAR(64) NOT NULL,
  scheme_primary_id VARCHAR(16) REFERENCES test_scheme_enum(scheme_id),
  scheme_secondary_id VARCHAR(16) REFERENCES test_scheme_enum(scheme_id),
  validation_primary_id VARCHAR(20) REFERENCES test_validation_enum(validation_id),
  validation_secondary_id VARCHAR(20) REFERENCES test_validation_enum(validation_id),
  sample_execution_note TEXT,
  mapping_source VARCHAR(128) DEFAULT 'scheme-map.json'
);

CREATE INDEX IF NOT EXISTS idx_category_minor_scheme_prefix ON test_category_minor_scheme(item_prefix);

-- 数据导入（28 条 · T1–T12）
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T1_SCHEMA', 'T1-', 'TS-01-DET', NULL, 'VS-02-CONTRACT', NULL, '契约', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T1_STATIC', 'T1-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '静态守卫', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T2_ROLE', 'T2-', 'TS-02-BND', NULL, 'VS-03-ZERO', NULL, '角色围栏', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T2_CAPABILITY', 'T2-', 'TS-02-BND', NULL, 'VS-03-ZERO', NULL, '能力边界', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T2_PAYLOAD', 'T2-', 'TS-02-BND', NULL, 'VS-03-ZERO', NULL, '载荷', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T3_FLOW', 'T3-', 'TS-05-CHAIN', NULL, 'VS-04-CHAIN-OK', NULL, '工作流', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T3_STATE', 'T3-', 'TS-05-CHAIN', NULL, 'VS-04-CHAIN-OK', NULL, '状态机', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T3_CONFIRM', 'T3-', 'TS-05-CHAIN', NULL, 'VS-04-CHAIN-OK', NULL, '确认两轮', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T4_ROUTE', 'T4-', 'TS-04-SET', NULL, 'VS-07-RATE-H', NULL, '路由策略', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T4_INTENT', 'T4-', 'TS-04-SET', NULL, 'VS-07-RATE-H', NULL, '意图规则', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T5_TOOL', 'T5-', 'TS-01-DET', NULL, 'VS-02-CONTRACT', NULL, '工具', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T5_MEMORY', 'T5-', 'TS-01-DET', NULL, 'VS-02-CONTRACT', NULL, '记忆', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T5_RETRIEVAL', 'T5-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '检索', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T6_SAFETY', 'T6-', 'TS-07-NEG', NULL, 'VS-09-BLOCK-H', NULL, '安全', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T6_PRIVACY', 'T6-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '隐私', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T6_BLOCK', 'T6-', 'TS-07-NEG', NULL, 'VS-09-BLOCK-H', NULL, '高风险', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T7_HTTP', 'T7-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, 'HTTP', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T7_STREAM', 'T7-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '流式', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T8_IDEM', 'T8-', 'TS-03-REP', NULL, 'VS-01-EXACT', NULL, '幂等', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T8_RECOVER', 'T8-', 'TS-03-REP', NULL, 'VS-01-EXACT', NULL, '恢复', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T9_LATENCY', 'T9-', 'TS-09-LOAD', NULL, 'VS-10-SLO-M', NULL, '延迟', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T9_CAPACITY', 'T9-', 'TS-09-LOAD', NULL, 'VS-10-SLO-M', NULL, '容量', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T10_COPY', 'T10-', 'TS-03-REP', NULL, 'VS-07-RATE-M', NULL, '文案', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T10_UI', 'T10-', 'TS-03-REP', NULL, 'VS-07-RATE-M', NULL, 'UI', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T11_LOG', 'T11-', 'TS-08-OBS', NULL, 'VS-05-PRESENCE', NULL, '日志', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T11_TRACE', 'T11-', 'TS-08-OBS', NULL, 'VS-05-PRESENCE', NULL, 'Trace', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T12_GOLDEN', 'T12-', 'TS-04-SET', NULL, 'VS-07-RATE-H', NULL, 'Golden', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor_scheme (category_minor_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('T12_REGRESS', 'T12-', 'TS-04-SET', NULL, 'VS-07-RATE-H', NULL, '回归', 'T1-T12') ON CONFLICT (category_minor_id) DO NOTHING;
