CREATE TABLE IF NOT EXISTS test_category_minor (
  project_code VARCHAR(64) NOT NULL DEFAULT 'fitness-agent',
  category_minor_id VARCHAR(64) PRIMARY KEY,
  category_major_id VARCHAR(64) REFERENCES test_category_major(category_major_id),
  name TEXT,
  sort_order SMALLINT
);

INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('A1_UNIT', 'A1', '单元/契约', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('A2_STATION', 'A2', '站级集成', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('A3_HTTP', 'A3', 'HTTP/服务', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('A4_E2E', 'A4', '全栈 E2E', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('A5_LOAD', 'A5', '压测/运维', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('A6_EVAL', 'A6', 'Eval/UAT', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B1_FRONT', 'B1', '前端幂等/SSE', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B1_OBS', 'B1', '站级观测', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B2_GUARD', 'B2', '门禁规则', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B2_OBS', 'B2', '站级观测', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B3_QUEUE', 'B3', '队列 Worker', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B3_OBS', 'B3', '站级观测', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B4_PIPELINE', 'B4', 'Pipeline', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B4_OBS', 'B4', '站级观测', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B5_PI', 'B5', 'Pi 契约', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B5_OBS', 'B5', '站级观测', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B6_SSE', 'B6', 'SSE 回传', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B6_OBS', 'B6', '站级观测', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('B_REL_LAW', 'B_REL', '可靠性法则', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_ENTRY', 'C1', '入口与会员上下文', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_INTENT', 'C1', '意图识别', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_MACRO', 'C1', '训练计划生成', 3) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_SESSION', 'C1', '单次训练内容', 4) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_SUM', 'C1', '训练总结', 5) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_STRAT', 'C1', '回复策略', 6) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_SAFE', 'C1', '安全审查', 7) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_IMPACT', 'C1', 'AI影响分析', 8) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_CONF', 'C1', '写库确认', 9) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_DEL', 'C1', '删除与重复', 10) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C1_OBJ', 'C1', '生成类对象清单', 11) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_BOUND', 'C2', '能力边界', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_STATE', 'C2', '会员状态', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_PAYLOAD', 'C2', '载荷边界', 3) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_MED', 'C2', '医疗安全', 4) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_FB', 'C2', '会员反馈', 5) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_QNR', 'C2', '健康问卷', 6) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_UX', 'C2', '速度与异常', 7) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C2_RISK', 'C2', '高风险清单', 8) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C3_MATRIX', 'C3', '能力矩阵', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C3_QUERY', 'C3', '查询场景', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C3_ALERT', 'C3', '管理提醒', 3) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C3_PAYLOAD', 'C3', '载荷边界', 4) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C3_PERM', 'C3', '权限与消歧', 5) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C3_RISK', 'C3', '高风险清单', 6) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_MEM', 'C4', '记忆与知识库', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_PAY', 'C4', '三端载荷矩阵', 2) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_PLAN_ST', 'C4', '训练计划状态机', 3) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_SESS_ST', 'C4', '课时状态机', 4) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_SUM_ST', 'C4', '总结状态机', 5) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_EVAL_ST', 'C4', '评估状态机', 6) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_QNR_ST', 'C4', '问卷状态机', 7) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_DATA', 'C4', '数据生命周期', 8) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('C4_CONF', 'C4', '写库确认横切', 9) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('D1_API', 'D1', '正常路径', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('D2_ERR', 'D2', '异常错误码', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('D3_SHELL', 'D3', '套壳联调', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('D4_FLD', 'D4', '202字段', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('D5_EVT', 'D5', 'SSE事件', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E1_PATH', 'E1', '决策路径', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E2_TOOL', 'E2', '工具调用', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E3_MEM', 'E3', '记忆上下文', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E4_STAB', 'E4', '稳定性', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E5_SEC', 'E5', '安全合规', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E6_EVAL', 'E6', 'Eval', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E_RISK_LIST', 'E_RISK', '高风险', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('E_SKILL_RT', 'E_SKILL', 'Skill路由', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('F1_PERF', 'F1', '性能', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('F2_REL', 'F2', '可靠性', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('F3_OBS', 'F3', '可观测概要', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('F4_DEPLOY', 'F4', '部署环境', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('F5_SYM', 'F5', '症状调参', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('F6_CAP', 'F6', '容量公式', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G1_PHASE', 'G1', '阶段反馈', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G2_QUEUE', 'G2', '排队感知', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G3_ERR', 'G3', '错误友好', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G4_SESS', 'G4', '会话续传', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G5_UI', 'G5', '结构化UI', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G6_DIFF', 'G6', '三端差异', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G7_STREAM', 'G7', '流式半截', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('G8_TIME', 'G8', '耗时指标', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H1_STATION', 'H1', '六站观测', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H2_FLD', 'H2', '日志字段', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H3_MEM', 'H3', '会员日志', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H4_MGR', 'H4', '管理日志', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H5_JRN', 'H5', 'journey漫游', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H6_SLS', 'H6', 'SLS监控', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H7_CHK', 'H7', '排障速查', 1) ON CONFLICT (category_minor_id) DO NOTHING;
INSERT INTO test_category_minor (category_minor_id, category_major_id, name, sort_order) VALUES ('H8_GAP', 'H8', '可观测缺口', 1) ON CONFLICT (category_minor_id) DO NOTHING;
