CREATE TABLE IF NOT EXISTS test_item_risk_link (
  project_code VARCHAR(64) NOT NULL DEFAULT 'fitness-agent',
  link_id VARCHAR(16) PRIMARY KEY,
  risk_item_id VARCHAR(64) NOT NULL REFERENCES test_item_detail(item_id) ON DELETE CASCADE,
  main_item_id VARCHAR(64) NOT NULL REFERENCES test_item_detail(item_id) ON DELETE CASCADE,
  relation_type_id VARCHAR(16) NOT NULL REFERENCES test_item_relation_type_enum(relation_type_id),
  risk_category VARCHAR(16) NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_bidirectional BOOLEAN NOT NULL DEFAULT TRUE,
  description TEXT,
  UNIQUE (risk_item_id, main_item_id, relation_type_id)
);
CREATE INDEX IF NOT EXISTS idx_risk_link_risk ON test_item_risk_link(risk_item_id);
CREATE INDEX IF NOT EXISTS idx_risk_link_main ON test_item_risk_link(main_item_id);

INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00001', 'E-RISK-001', 'C1-INTENT-001', 'GUARD', 'E_AGENT', TRUE, TRUE, '问答 vs 生成：text 不写库') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00002', 'E-RISK-001', 'E1-PATH-001', 'VERIFY', 'E_AGENT', FALSE, TRUE, '决策路径：问答 vs 生成') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00003', 'E-RISK-002', 'C1-INTENT-007', 'GUARD', 'E_AGENT', TRUE, TRUE, '草案 vs 正式草稿区分') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00004', 'E-RISK-002', 'C1-MACRO-007', 'VERIFY', 'E_AGENT', FALSE, TRUE, '表单后草稿态非正式') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00005', 'E-RISK-003', 'C1-ENTRY-002', 'GUARD', 'E_AGENT', TRUE, TRUE, '通用入口先识别会员') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00006', 'E-RISK-003', 'C1-ENTRY-001', 'VERIFY', 'E_AGENT', FALSE, TRUE, '通用问答不进入 plan_form') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00007', 'E-RISK-004', 'C1-ENTRY-005', 'GUARD', 'E_AGENT', TRUE, TRUE, '同名消歧列表') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00008', 'E-RISK-004', 'C3-PERM-003', 'VERIFY', 'E_AGENT', FALSE, TRUE, '管理端同名消歧') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00009', 'E-RISK-005', 'C1-ENTRY-004', 'GUARD', 'E_AGENT', TRUE, TRUE, '会员 A/B 上下文隔离') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00010', 'E-RISK-005', 'E3-MEM-003', 'VERIFY', 'E_AGENT', FALSE, TRUE, '多 session 不串上下文') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00011', 'E-RISK-006', 'C1-CONF-003', 'GUARD', 'E_AGENT', TRUE, TRUE, '口语确认不写库') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00012', 'E-RISK-006', 'C1-INTENT-005', 'VERIFY', 'E_AGENT', FALSE, TRUE, '「好的/可以」非正式确认') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00013', 'E-RISK-006', 'C4-CONF-001', 'VERIFY', 'E_AGENT', FALSE, TRUE, '横切确认规则') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00014', 'E-RISK-007', 'C1-CONF-001', 'GUARD', 'E_AGENT', TRUE, TRUE, '多待确认先选对象') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00015', 'E-RISK-008', 'C1-STRAT-001', 'GUARD', 'E_AGENT', TRUE, TRUE, '疼痛先安全策略') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00016', 'E-RISK-008', 'C1-INTENT-008', 'VERIFY', 'E_AGENT', FALSE, TRUE, '疼痛+生成先安全') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00017', 'E-RISK-008', 'C1-SAFE-005', 'VERIFY', 'E_AGENT', FALSE, TRUE, '安全审查阻断生成') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00018', 'E-RISK-008', 'E-SKILL-PAIN-001', 'VERIFY', 'E_AGENT', FALSE, TRUE, 'training-safety-pain skill') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00019', 'E-RISK-009', 'C1-MACRO-003', 'GUARD', 'E_AGENT', TRUE, TRUE, '指标 current 无来源为空') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00020', 'E-RISK-009', 'C1-MACRO-005', 'GUARD', 'E_AGENT', TRUE, TRUE, '体测表不编造') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00021', 'E-RISK-009', 'B4-PREP-002', 'VERIFY', 'E_AGENT', FALSE, TRUE, 'Pipeline 指标空值 gate') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00022', 'E-RISK-010', 'C3-PROG-001', 'GUARD', 'E_AGENT', TRUE, TRUE, '管理摘要基于真实数据') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00023', 'E-RISK-010', 'C3-RISK-005', 'VERIFY', 'E_AGENT', FALSE, TRUE, '风险清单：禁止 AI 编造') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00024', 'C2-RISK-001', 'C2-BOUND-001', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '禁止生成训练计划') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00025', 'C2-RISK-001', 'C2-BOUND-002', 'VERIFY', 'C2_MEMBER', FALSE, TRUE, '禁止生成课时') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00026', 'C2-RISK-002', 'C2-PAYLOAD-001', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '不得返回 plan_form_data') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00027', 'C2-RISK-002', 'C2-PAYLOAD-004', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '不得 message_type=plan_form') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00028', 'C2-RISK-002', 'C4-PAY-001', 'VERIFY', 'C2_MEMBER', FALSE, TRUE, '三端载荷矩阵') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00029', 'C2-RISK-003', 'C2-MED-001', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '胸闷停止训练') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00030', 'C2-RISK-003', 'C2-BOUND-008', 'VERIFY', 'C2_MEMBER', FALSE, TRUE, '疼痛反馈停练') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00031', 'C2-RISK-003', 'C2-MED-002', 'VERIFY', 'C2_MEMBER', FALSE, TRUE, '剧烈疼痛就医') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00032', 'C2-RISK-004', 'C2-FB-001', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '反馈不自动改计划') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00033', 'C2-RISK-005', 'C2-BOUND-007', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '拒绝后 active 不变') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00034', 'C2-RISK-006', 'G5-UI-004', 'GUARD', 'C2_MEMBER', TRUE, TRUE, '会员端不渲染 coach 组件') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00035', 'C2-RISK-006', 'C4-PAY-001', 'VERIFY', 'C2_MEMBER', FALSE, TRUE, '载荷矩阵会员列') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00036', 'C2-RISK-007', 'H3-MEM-001', 'DETECT', 'C2_MEMBER', TRUE, TRUE, '计划确认/拒绝留痕') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00037', 'C2-RISK-007', 'C2-BOUND-006', 'VERIFY', 'C2_MEMBER', FALSE, TRUE, '确认流程有日志') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00038', 'C3-RISK-001', 'C3-PAYLOAD-001', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '禁止 plan_form message_type') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00039', 'C3-RISK-001', 'C3-PAYLOAD-002', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '禁止 plan_form_data') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00040', 'C3-RISK-001', 'C3-BOUND-001', 'VERIFY', 'C3_MANAGER', FALSE, TRUE, '禁止生成训练计划') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00041', 'C3-RISK-002', 'C3-BOUND-003', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '禁止替教练确认') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00042', 'C3-RISK-003', 'C3-PERM-001', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '非本店拒绝') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00043', 'C3-RISK-003', 'C3-MEM-001', 'VERIFY', 'C3_MANAGER', FALSE, TRUE, '会员查询门店范围') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00044', 'C3-RISK-004', 'C3-PERM-003', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '多李四消歧') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00045', 'C3-RISK-004', 'C3-PERM-004', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '对象不清追问') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00046', 'C3-RISK-004', 'C3-COACH-003', 'VERIFY', 'C3_MANAGER', FALSE, TRUE, '多王教练消歧') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00047', 'C3-RISK-005', 'C3-PROG-001', 'GUARD', 'C3_MANAGER', TRUE, TRUE, '进展摘要不编造') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00048', 'C3-RISK-005', 'E-RISK-010', 'VERIFY', 'C3_MANAGER', FALSE, TRUE, 'Agent 伪造事实风险') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00049', 'C3-RISK-006', 'C3-COACH-004', 'DETECT', 'C3_MANAGER', TRUE, TRUE, 'interaction_log_id 可回查') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00050', 'C3-RISK-006', 'H4-MGR-002', 'DETECT', 'C3_MANAGER', FALSE, TRUE, '管理操作前后状态留痕') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00051', 'C3-RISK-006', 'H2-FLD-019', 'DETECT', 'C3_MANAGER', FALSE, TRUE, '日志 19 项 interaction_log_id') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00052', 'F5-SYM-001', 'B3-OBS-001', 'SYMPTOM', 'F5_SYMPTOM', TRUE, TRUE, '排队久→pending 深度') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00053', 'F5-SYM-001', 'G2-QUEUE-001', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, 'queue_meta UX') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00054', 'F5-SYM-002', 'D2-SUB-005', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, 'submit 503') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00055', 'F5-SYM-002', 'G2-QUEUE-002', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, '503 友好提示') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00056', 'F5-SYM-003', 'B2-CIRCUIT-001', 'SYMPTOM', 'F5_SYMPTOM', TRUE, TRUE, 'DB 熔断') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00057', 'F5-SYM-003', 'H1-S02-002', 'DETECT', 'F5_SYMPTOM', FALSE, TRUE, '熔断状态观测') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00058', 'F5-SYM-004', 'B3-RETRY-001', 'SYMPTOM', 'F5_SYMPTOM', TRUE, TRUE, 'LLM 429 重试') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00059', 'F5-SYM-004', 'E4-STAB-002', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, 'LLM failed 留痕') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00060', 'F5-SYM-005', 'F2-POOL-001', 'SYMPTOM', 'F5_SYMPTOM', TRUE, TRUE, 'RDS 连接池') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00061', 'F5-SYM-005', 'F6-CAP-002', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, '连接数公式') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00062', 'F5-SYM-006', 'H1-S04-001', 'DETECT', 'F5_SYMPTOM', TRUE, TRUE, 'stages_ms 分段') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00063', 'F5-SYM-007', 'D1-READY-001', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, 'ready 探针') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00064', 'F5-SYM-008', 'B6-TIMEOUT-001', 'SYMPTOM', 'F5_SYMPTOM', TRUE, TRUE, 'SSE 超时断流') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00065', 'F5-SYM-008', 'G7-STREAM-001', 'SYMPTOM', 'F5_SYMPTOM', FALSE, TRUE, '半截不写档') ON CONFLICT (link_id) DO NOTHING;
INSERT INTO test_item_risk_link (link_id, risk_item_id, main_item_id, relation_type_id, risk_category, is_primary, is_bidirectional, description) VALUES ('RLK00066', 'F5-SYM-009', 'F1-CONC-001', 'SYMPTOM', 'F5_SYMPTOM', TRUE, TRUE, 'BFF/Worker CPU 争用') ON CONFLICT (link_id) DO NOTHING;
