CREATE TABLE IF NOT EXISTS test_item_prefix_scheme (
  project_code VARCHAR(64) NOT NULL DEFAULT 'fitness-agent',
  mapping_id VARCHAR(16) PRIMARY KEY,
  item_prefix VARCHAR(64) NOT NULL,
  scheme_primary_id VARCHAR(16) REFERENCES test_scheme_enum(scheme_id),
  scheme_secondary_id VARCHAR(16) REFERENCES test_scheme_enum(scheme_id),
  validation_primary_id VARCHAR(20) REFERENCES test_validation_enum(validation_id),
  validation_secondary_id VARCHAR(20) REFERENCES test_validation_enum(validation_id),
  sample_execution_note TEXT,
  mapping_source VARCHAR(128)
);
CREATE INDEX IF NOT EXISTS idx_prefix_scheme ON test_item_prefix_scheme(item_prefix);

-- 数据导入（19 条 · 仅 .pi）
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0001', 'PI-SCENE-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, 'scene_code 围栏', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0002', 'PI-EMIT-', 'TS-01-DET', NULL, 'VS-02-CONTRACT', NULL, 'emit/outbox 契约', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0003', 'PI-MACRO-', 'TS-05-CHAIN', NULL, 'VS-04-CHAIN-OK', NULL, '宏观计划工作流', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0004', 'PI-SESS-', 'TS-05-CHAIN', NULL, 'VS-04-CHAIN-OK', NULL, '单节课工作流', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0005', 'PI-SUM-', 'TS-02-BND', NULL, 'VS-02-CONTRACT', NULL, '课后总结', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0006', 'PI-DEL-', 'TS-05-CHAIN', NULL, 'VS-04-CHAIN-OK', NULL, '删除两轮', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0007', 'PI-FOLLOW-', 'TS-04-SET', NULL, 'VS-03-ZERO', NULL, '好的兑现/确认边界', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0008', 'PI-ENTRY-', 'TS-04-SET', NULL, 'VS-07-RATE-H', NULL, '教练入口', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0009', 'PI-SAFE-', 'TS-07-NEG', NULL, 'VS-09-BLOCK-H', NULL, '安全/医学/评估', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0010', 'PI-ARCH-', 'TS-02-BND', NULL, 'VS-02-CONTRACT', NULL, '档案确认', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0011', 'PI-MEMB-', 'TS-02-BND', NULL, 'VS-02-CONTRACT', NULL, '会员端边界', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0012', 'PI-MGR-', 'TS-02-BND', NULL, 'VS-02-CONTRACT', NULL, '店长端', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0013', 'PI-SKILL-', 'TS-04-SET', NULL, 'VS-07-RATE-H', NULL, '咨询 skill', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0014', 'PI-MEM-', 'TS-01-DET', NULL, 'VS-02-CONTRACT', NULL, 'memory_ops', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0015', 'PI-TOOL-', 'TS-01-DET', NULL, 'VS-02-CONTRACT', NULL, '工具白名单', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0016', 'PI-THINK-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '思考脱敏', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0017', 'PI-HTTP-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '.pi HTTP', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0018', 'PI-STATIC-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, '静态守卫', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
INSERT INTO test_item_prefix_scheme (mapping_id, item_prefix, scheme_primary_id, scheme_secondary_id, validation_primary_id, validation_secondary_id, sample_execution_note, mapping_source) VALUES ('MAP0019', 'PI-WIKI-', 'TS-01-DET', NULL, 'VS-01-EXACT', NULL, 'wiki 检索', 'PI-方案映射.md') ON CONFLICT (mapping_id) DO NOTHING;
